### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by perliedman**
Since the latest released version is very hard to build on a modern Ubuntu machine (at least for me!), I have updated the dependencies to modern versions. Most importantly, mapnik is updated to 4.2.1.

I also accepted all of `npm audit`'s suggested fixes, even for possibly breaking changes. This in turn made be replace jscs with eslint.

Happy to break this PR into separate pieces if that makes more sense.

### CODE REVIEW

**Comment by perliedman** [comment]
BTW, the tests break in Node 4, since it isn't compatible with eslint. Don't know if Node 4 is still a priority to the project (Node 4 has reached end of life). As mentioned above, I am happy to split of the eslint parts to a separate PR if this is an issue for you.

**Comment by perliedman** [comment]
Hi @mourner! :wave: Great feedback as always!

I have perfomed the changes, just let me know if there is something more to be done to get this merged. For example, should I get rid of the Node 4 builds in `.travis.yml` and maybe add Node 8 and 10 instead?

**Comment by mourner** [comment]
Oh, sure! Node 4 reached End of Life (no further updates even if critical) a year ago, and Node 6 reaches it next month. So I think we should switch to versions 8 and “node” (for latest). @mapsam what do you think?

**Comment by perliedman** [comment]
Appears there are no pre-built binaries for gdal 0.9.8 and Node 11, so Travis will compile gdal which might take some time (but hopefully work :grimacing: ).

**Comment by perliedman** [comment]
Update: Travis failed to build gdal for Node 11. I guess we could fix the env to allow this, but for now I just use Node 10, which has prebuilt gdal binaries. Hope that is ok.

**Comment by mourner** [comment]
I think it’s fine! Node 11 is not LTS anyway.

**Comment by mapsam** [comment]
> So I think we should switch to versions 8 and “node” (for latest)

Agree! Thanks @perliedman + @mourner 😄

**Comment by perliedman** [comment]
So good to merge?

Also, if it is not too much trouble, I have similar PRs, but a bit simpler, open for tilelive-mapnik (https://github.com/mapbox/tilelive-mapnik/pull/124) and tilelive-bridge (https://github.com/mapbox/tilelive-bridge/pull/103).

**Comment by mapsam** [comment]
Sorry @perliedman - I assumed @mourner was taking the merge/release on but should have checked with him first. Merging now!

**Pull request merged**
