### PR TITLE
node-gdal@0.8.0

### PR DESCRIPTION
**Pull request by springmeyer**
refs https://github.com/naturalatlas/node-gdal/releases/tag/v0.8.0

### CODE REVIEW

**Comment by mojodna** [comment]
Yes please. (`gdal@0.7.2` doesn't include a binary for node-5.4, probably other versions)

**Comment by mojodna** [comment]
@springmeyer is anything blocking this (that I can help with)? merging this would save [POSM](https://github.com/americanredcross/posm) some time spent on compilation.

**Comment by springmeyer** [comment]
@mojodna - merged.

**Comment by mojodna** [comment]
Yay!

(A new release wouldn't go amiss either ;-)

**Comment by mojodna** [comment]
(But I've only given you about 90s...)

**Comment by springmeyer** [comment]
Waiting on travis before publishing: https://travis-ci.org/mapbox/mapnik-omnivore/builds/104212385

**Comment by mojodna** [comment]
:+1:

Thanks!!

**Comment by jharpster** [comment]
:+1:

**Comment by springmeyer** [comment]
mapnik-omnivore@7.1.0 is published /cc @mojodna

**Pull request merged**
