### PR TITLE
Correctly fetch band info

### PR DESCRIPTION
**Pull request by mojodna**
This was previously only picking up the last band present in a multi-band image.

### CODE REVIEW

**Comment by mojodna** [comment]
(This is failing because it can't pull a coverage report from coveralls, not because of anything having to do with this PR.)

**Comment by mojodna** [comment]
Bump.

**Comment by GretaCB** [comment]
Great catch @mojodna , and sorry for the delay on scooping this up. Mind merging master into your branch?

**Comment by mojodna** [comment]
Done.  Thanks!

**Comment by GretaCB** [comment]
Also, just FYI, I am going to [merge a PR shortly](https://travis-ci.org/mapbox/mapnik-omnivore/builds/61499794) for the new `node-gdal` 0.4.4 binaries. Just waiting on tests

**Pull request merged**
