### PR TITLE
Module-based refactor

### PR DESCRIPTION
**Pull request by rclark**
Rerolled from #74

### CODE REVIEW

**Comment by GretaCB** [comment]
@springmeyer Tests are good. @rclark did some great PATH troubleshooting to get appveyor happy. I'll be throwing this branch into unpacker and studio today to see what breaks. Once those are proven safe with the refactor, we are good to go whenever you have some bandwidth for binaries.

**Comment by springmeyer** [comment]
> good to go whenever you have some bandwidth for binaries.

Done, I've published the missing binaries for Visual studio 2014 and the existing node-gdal v0.4.1 release. So node-gdal 0.4.1 is good to go and all appveyor tests should be passing. Let me know if not.

**Comment by GretaCB** [comment]
Update: 
- Studio: Good to go at https://github.com/mapbox/mapbox-studio/pull/1199
- unpacker: Not good to go at https://github.com/mapbox/unpacker/pull/406. Slugger keeps failing. I wonder if this has something to do with having tarball deps. Once that is set, need to publish the relevant deps and test in staging.

cc @rclark

**Comment by GretaCB** [comment]
Update: unpacker is good to go. Slugger mysteriously started passing. 

Deploying to staging for testing.

cc @rclark

**Comment by rclark** [comment]
Forgot to say: HURRAY! This is awesome.

**Pull request merged**
